version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: always
    # Run as normal user
    #user: 1000:1000
    # Environment must either be "test" or "prod" passed over the shell (e.g. ENVIRONMENT=prod docker-compose up)
    env_file: ${ENVIRONMENT}.env
    volumes:
      # Referencing the server-conf git repo
      - ../../server-conf/minecraft-server:/conf:ro
      - /Data/docker_data/minecraft_server:/data
    ports:
      - "25565:25565/tcp"
    #cap_add:
    #  - NET_ADMIN
    #network_mode: host
    #privileged: true
    #stdin_open: true
    #tty: true

