version: '3.7'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    # Run as normal user
    #user: 1000:1000
    # Environment must either be "test" or "prod" passed over the shell (e.g. ENVIRONMENT=prod docker-compose up)
    env_file: ${ENVIRONMENT}.env
    volumes:
      # Referencing the server-conf git repo
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bjorn_aelvoet/docker_data/portainer:/data 
    ports:
      - "9000:9000/tcp"
      - "8000:8000/tcp"
    #cap_add:
    #  - NET_ADMIN
    #network_mode: host
    #privileged: true
    #stdin_open: true
    #tty: true

    #build:
    #  dockerfile: Dockerfile
    #  #args:
    #  #  #No args defined
    #  #  - DUMMY=dummy
    #  context: .
