version: '3.7'

services:
  glances:
    image: nicolargo/glances
    container_name: glances
    restart: always
    # Run as normal user
    #user: 1000:1000
    # Environment must either be "test" or "prod" passed over the shell (e.g. ENVIRONMENT=prod docker-compose up)
    env_file: ${ENVIRONMENT}.env
    volumes:
      # Referencing the server-conf git repo
      - ../server-conf/glances/glances.conf:/glances/conf/glances.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "61208-61209:61208-61209/tcp"
    devices:
      - /dev/sda1:/dev/sda1
      - /dev/sda2:/dev/sda2
      - /dev/sdb1:/dev/sdb1
      #- /dev/sdc1:/dev/sdc1  
    pid: host
    #cap_add:
    #  - NET_ADMIN
    network_mode: host
    #privileged: true
    #stdin_open: true
    #tty: true
