version: '3.7'

services:
  samba:
    image: bjornaelvoet/samba
    container_name: samba
    restart: always
    # Run as normal user
    #user: 1000:1000
    # Environment must either be "test" or "prod" passed over the shell (e.g. ENVIRONMENT=prod docker-compose up)
    env_file: ${ENVIRONMENT}.env
    volumes:
      # Referencing the server-conf git repo
      - ../../server-conf/samba:/conf:ro
      - /Data/bjorn_aelvoet:/home/bjorn_aelvoet
      - /Data/eva_vandevelde:/home/eva_vandevelde
      - /Data/jasper_aelvoet:/home/jasper_aelvoet
      - /Data/daan_aelvoet:/home/daan_aelvoet
      - /Data/share:/home/share
      - /Data/media:/home/media
      - /hdd_extern/media:/home/media_nobackup
      - /Data/media/music/Official:/home/itunes
      - /hdd_extern:/home/hdd_extern
      - /hdd_backup:/home/hdd_backup
    ports:
      - "445:445/tcp"
    #cap_add:
    #  - NET_ADMIN
    #network_mode: host
    #privileged: true
    #stdin_open: true
    #tty: true

    build:
      dockerfile: Dockerfile
      #args:
      #  #No args defined
      #  - DUMMY=dummy
      context: .
