version: '3.7'

services:
  dnsmasq:
    image: bjornaelvoet/dnsmasq
    container_name: dnsmasq
    restart: always
    # Environment must either be "test" or "prod" passed over the shell (e.g. ENVIRONMENT=prod docker-compose up)
    env_file: ./${ENVIRONMENT}.env
    volumes:
      # Referencing the server-conf git repo
      - ../server-conf/dnsmasq:/conf:ro
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    network_mode: host
    #privileged: true
    #stdin_open: true
    #tty: true

    build:
      dockerfile: Dockerfile
      #args:
      #  #No args defined
      #  - DUMMY=dummy
      context: .

